## configure to forward packets

- name: enable packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: enable secure redirects
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 1

- name: disable accept redirects
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0

- name: disable source routing
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0

- name: disable send redirects
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0



